-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dodatki
(
    id_dodatku serial NOT NULL,
    nazwa character varying(50) COLLATE pg_catalog."default" NOT NULL,
    cena_dodatkowa numeric(5, 2) DEFAULT 0,
    CONSTRAINT dodatki_pkey PRIMARY KEY (id_dodatku)
);

CREATE TABLE IF NOT EXISTS public.uzytkownicy
(
    id_uzytkownika serial NOT NULL,
    email character varying(100) NOT NULL,
    haslo character varying(100) NOT NULL,
    rola  character varying(20),
    CONSTRAINT uzytkownicy_pkey PRIMARY KEY (id_uzytkownika)
);

CREATE TABLE IF NOT EXISTS public.adresy
(
    id_adresu serial NOT NULL,
    miasto character varying(100) NOT NULL,
    ulica character varying(100) NOT NULL,
    numer_budynku character varying(100) NOT NULL,
    numer_mieszkania character varying(100),
    CONSTRAINT adresy_pkey PRIMARY KEY (id_adresu)
);

CREATE TABLE IF NOT EXISTS public.pizze
(
    id_pizzy serial NOT NULL,
    nazwa character varying(50) COLLATE pg_catalog."default",
    cena numeric(6, 2),
    CONSTRAINT pizze_pkey PRIMARY KEY (id_pizzy)
);

CREATE TABLE IF NOT EXISTS public.zamowienia
(
    id_zamowienia serial NOT NULL,
    id_adresu integer,
    id_uzytkownika integer,
    imie character varying(30) COLLATE pg_catalog."default" NOT NULL,
    nazwisko character varying(30) COLLATE pg_catalog."default" NOT NULL,
    telefon character varying(15) COLLATE pg_catalog."default" NOT NULL,
    adres character varying(100) COLLATE pg_catalog."default" NOT NULL,
    data_zamowienia timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'złożone'::character varying,
    cena_calkowita numeric(8, 2),
    rabat numeric(5, 2) DEFAULT 0,
    CONSTRAINT zamowienia_pkey PRIMARY KEY (id_zamowienia)
);

CREATE TABLE IF NOT EXISTS public.zamowienie_dodatki
(
    id_zamowienia_dodatku serial NOT NULL,
    id_zamowienia_pizzy integer,
    id_dodatku integer,
    ilosc integer DEFAULT 1,
    CONSTRAINT zamowienie_dodatki_pkey PRIMARY KEY (id_zamowienia_dodatku)
);

CREATE TABLE IF NOT EXISTS public.zamowienie_pizze
(
    id_zamowienia_pizzy serial NOT NULL,
    id_zamowienia integer,
    id_pizzy integer,
    ilosc integer DEFAULT 1,
    cena_pizzy numeric(6, 2),
    CONSTRAINT zamowienie_pizze_pkey PRIMARY KEY (id_zamowienia_pizzy)
);

ALTER TABLE IF EXISTS public.zamowienia
    ADD CONSTRAINT zamowienia_id_uzytkownika_fkey FOREIGN KEY (id_uzytkownika)
    REFERENCES public.uzytkownicy (id_uzytkownika) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zamowienie_dodatki
    ADD CONSTRAINT zamowienie_dodatki_id_dodatku_fkey FOREIGN KEY (id_dodatku)
    REFERENCES public.dodatki (id_dodatku) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zamowienie_dodatki
    ADD CONSTRAINT zamowienie_dodatki_id_zamowienia_pizzy_fkey FOREIGN KEY (id_zamowienia_pizzy)
    REFERENCES public.zamowienie_pizze (id_zamowienia_pizzy) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zamowienie_pizze
    ADD CONSTRAINT zamowienie_pizze_id_pizzy_fkey FOREIGN KEY (id_pizzy)
    REFERENCES public.pizze (id_pizzy) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.zamowienie_pizze
    ADD CONSTRAINT zamowienie_pizze_id_zamowienia_fkey FOREIGN KEY (id_zamowienia)
    REFERENCES public.zamowienia (id_zamowienia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

ALTER TABLE public.zamowienia
    ADD CONSTRAINT zamowienia_adresy_fkey FOREIGN KEY (id_adresu)
    REFERENCES public.adresy(id_adresu)
    ON UPDATE CASCADE
    ON DELETE SET NULL;

END;